name: Test Code

on:
  push:
    branches:
      - Feature-AA-Automated-Testing

jobs:
  test:
    runs-on: windows-latest
    steps:
    
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements.txt"
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test code
      run: python src/BODSDataExtractor/example.py
